DROP DATABASE CGPA_CALC;

CREATE DATABASE CGPA_CALC;

USE CGPA_CALC;

CREATE TABLE STUDENT(
    REGNO VARCHAR(10),
    ENTRY_MODE CHAR, -- R OR L
    CGPA FLOAT
);

CREATE TABLE COURSES(
    COURSE_CODE VARCHAR(10),
    CREDITS FLOAT
);

ALTER TABLE COURSES ADD SEM INT;